title: "AI Blog"
email: "contact@dataengineer.net.br"
description: >- 
  This blog explores the world of Artificial Intelligence, Machine Learning, Data, and emerging technologies. Stay informed with weekly insights and thought-provoking articles.
baseurl: "/blog"
url: "https://marcos-data-engineer.github.io"
twitter_username: your_twitter_handle
github_username: marcos-data-engineer
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed