# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies

on:
  push:
    branches: ["main"] # Altere para a sua branch principal se não for 'main'
  pull_request:
    branches: ["main"] # Altere para a sua branch principal se não for 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not required for Jekyll 4, but can be useful for history

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Pode ajustar para a sua versão de Ruby, ex: '3.2', '3.3'
          bundler-cache: true # Installs dependencies with Bundler

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "/blog" # Adicione --baseurl "/blog" aqui

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site' # Onde o Jekyll gera o site construído

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4